###Sign up f/app
POST http://localhost:3000/signup
Content-Type: application/json

{
    "email": "test@test.com",
    "password":"mypassword"
}

###Sign in
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "test@test.com",
    "password":"mypassword"
}

###Token check
GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWYyMjA1MWM4ZDc0ODgyNGQwMjc0NTEiLCJpYXQiOjE2NDMyNTc5Mzd9.6bB60cvD-kvWzb2GxVgkkS6fM5FKJnxHNdMKyB4w0gs

###Get Tracks f/user
GET http://localhost:3000/tracks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWYyODU5YTI0NTZkODZkZWNjMTNlNDUiLCJpYXQiOjE2NDMzNTE0OTV9.72VYFqGNu8xn8l4SGHWWl-5zdCT_YfjwmcxJXVWr7EQ

###Create new Track
POST http://localhost:3000/tracks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWYyODU5YTI0NTZkODZkZWNjMTNlNDUiLCJpYXQiOjE2NDMzNTE0OTV9.72VYFqGNu8xn8l4SGHWWl-5zdCT_YfjwmcxJXVWr7EQ

{
  "name": "New track",
  "locations": [
    {
      "timestamp": 100000000,
      "coords": {
        "latitude": 100,
        "longitude": 100,
        "altitude": 100,
        "accuracy": 100,
        "heading": 100,
        "speed": 100
      }
    }
  ]
}